version: "3"
services:
  sonarqube-prometheus-exporter:
    image: sonarqube-prometheus-exporter
    ports:
      - "8080:8080"
    environment:
      - SONAR_URL=http://localhost:9000/
      - SONAR_USER=admin
      - SONAR_PASSWORD=admin
    build:
      context: .
      dockerfile: Dockerfile