version: "3"
services:
  sonarqube-prometheus-exporter:
    image: sonarqube-prometheus-exporter
    ports:
      - "8080:8080"
    environment:
      - SONAR_URL=http://65.0.42.18:9000
      - SONAR_USER=admin
      - SONAR_PASSWORD=Admin@123
    build:
      context: .
      dockerfile: Dockerfile